In [75]:
import numpy as np
import pandas as pd
import openpyxl
import joblib

In [76]:
df=pd.read_excel("../raw data/dd.xlsx")
df.head()

,Customer_ID,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,CUST_0110,NaN,87559.0,677.0,67443.0,26,1,Not Graduate,No,Approved
1,CUST_0011,44.0,25955.0,661.0,11896.0,16,1,Graduate,No,Approved
2,CUST_0185,52.0,18000.0,784.0,19197.0,27,4,Graduate,No,Approved
3,CUST_0078,21.0,28647.0,652.0,58469.0,0,3,Graduate,No,Approved
4,CUST_0539,21.0,78620.0,772.0,46738.0,0,4,Graduate,No,Approved

In [77]:
df.drop(columns=['Customer_ID'], inplace=True)

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               593 non-null    float64
 1   Annual_Income     590 non-null    float64
 2   Credit_Score      593 non-null    float64
 3   Loan_Amount       590 non-null    float64
 4   Employment_Years  608 non-null    int64
 5   Dependents        608 non-null    int64
 6   Education         594 non-null    str
 7   Self_Employed     596 non-null    str
 8   Loan_Status       608 non-null    str
dtypes: float64(4), int64(2), str(3)
memory usage: 54.3 KB

In [79]:
df.columns

Index(['Age', 'Annual_Income', 'Credit_Score', 'Loan_Amount',
       'Employment_Years', 'Dependents', 'Education', 'Self_Employed',
       'Loan_Status'],
      dtype='str')

In [80]:
df.dtypes

Age                 float64
Annual_Income       float64
Credit_Score        float64
Loan_Amount         float64
Employment_Years      int64
Dependents            int64
Education               str
Self_Employed           str
Loan_Status             str
dtype: object

In [81]:
df.duplicated().sum()

np.int64(8)

In [82]:
df.drop_duplicates(inplace=True)

In [83]:
df.isna().sum()

Age                 15
Annual_Income       18
Credit_Score        15
Loan_Amount         18
Employment_Years     0
Dependents           0
Education           12
Self_Employed       12
Loan_Status          0
dtype: int64

In [84]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df.isna().sum()

Age                  0
Annual_Income       18
Credit_Score        15
Loan_Amount         18
Employment_Years     0
Dependents           0
Education           12
Self_Employed       12
Loan_Status          0
dtype: int64

In [85]:
df['Annual_Income']=df['Annual_Income'].fillna(df['Annual_Income'].mean())
df.isna().sum()

Age                  0
Annual_Income        0
Credit_Score        15
Loan_Amount         18
Employment_Years     0
Dependents           0
Education           12
Self_Employed       12
Loan_Status          0
dtype: int64

In [86]:
df['Credit_Score']=df['Credit_Score'].fillna(df['Credit_Score'].mean())
df.isna().sum()

Age                  0
Annual_Income        0
Credit_Score         0
Loan_Amount         18
Employment_Years     0
Dependents           0
Education           12
Self_Employed       12
Loan_Status          0
dtype: int64

In [87]:
df['Loan_Amount']=df['Loan_Amount'].fillna(df['Loan_Amount'].mean())
df.isna().sum()

Age                  0
Annual_Income        0
Credit_Score         0
Loan_Amount          0
Employment_Years     0
Dependents           0
Education           12
Self_Employed       12
Loan_Status          0
dtype: int64

In [88]:
df['Education']=df['Education'].ffill()
df.isna().sum()

Age                  0
Annual_Income        0
Credit_Score         0
Loan_Amount          0
Employment_Years     0
Dependents           0
Education            0
Self_Employed       12
Loan_Status          0
dtype: int64

In [89]:
df['Self_Employed']=df['Self_Employed'].bfill()
df.isna().sum()

Age                 0
Annual_Income       0
Credit_Score        0
Loan_Amount         0
Employment_Years    0
Dependents          0
Education           0
Self_Employed       0
Loan_Status         0
dtype: int64

In [90]:
df.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 607
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               600 non-null    float64
 1   Annual_Income     600 non-null    float64
 2   Credit_Score      600 non-null    float64
 3   Loan_Amount       600 non-null    float64
 4   Employment_Years  600 non-null    int64
 5   Dependents        600 non-null    int64
 6   Education         600 non-null    str
 7   Self_Employed     600 non-null    str
 8   Loan_Status       600 non-null    str
dtypes: float64(4), int64(2), str(3)
memory usage: 58.3 KB

In [91]:
df.head()

,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,41.451282,87559.0,677.0,67443.0,26,1,Not Graduate,No,Approved
1,44.000000,25955.0,661.0,11896.0,16,1,Graduate,No,Approved
2,52.000000,18000.0,784.0,19197.0,27,4,Graduate,No,Approved
3,21.000000,28647.0,652.0,58469.0,0,3,Graduate,No,Approved
4,21.000000,78620.0,772.0,46738.0,0,4,Graduate,No,Approved

In [92]:
df['Education']=df['Education'].str.lower()
df['Education']=df['Education'].str.strip()

In [93]:
df.head()

,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,41.451282,87559.0,677.0,67443.0,26,1,not graduate,No,Approved
1,44.000000,25955.0,661.0,11896.0,16,1,graduate,No,Approved
2,52.000000,18000.0,784.0,19197.0,27,4,graduate,No,Approved
3,21.000000,28647.0,652.0,58469.0,0,3,graduate,No,Approved
4,21.000000,78620.0,772.0,46738.0,0,4,graduate,No,Approved

In [94]:
df.to_csv("../clean data/cleaned_data.csv", index=False)

In [95]:
df = pd.read_csv('../clean data/cleaned_data.csv')

In [96]:
df.head()

,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,41.451282,87559.0,677.0,67443.0,26,1,not graduate,No,Approved
1,44.000000,25955.0,661.0,11896.0,16,1,graduate,No,Approved
2,52.000000,18000.0,784.0,19197.0,27,4,graduate,No,Approved
3,21.000000,28647.0,652.0,58469.0,0,3,graduate,No,Approved
4,21.000000,78620.0,772.0,46738.0,0,4,graduate,No,Approved

In [97]:
df.head()

,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,41.451282,87559.0,677.0,67443.0,26,1,not graduate,No,Approved
1,44.000000,25955.0,661.0,11896.0,16,1,graduate,No,Approved
2,52.000000,18000.0,784.0,19197.0,27,4,graduate,No,Approved
3,21.000000,28647.0,652.0,58469.0,0,3,graduate,No,Approved
4,21.000000,78620.0,772.0,46738.0,0,4,graduate,No,Approved

In [98]:
df['Self_Employed']=df['Self_Employed'].str.lower()
df['Self_Employed']=df['Self_Employed'].str.strip()

In [99]:
df.to_csv("../clean data/cleaned_data.csv", index=False)

In [100]:
df

,Age,Annual_Income,Credit_Score,Loan_Amount,Employment_Years,Dependents,Education,Self_Employed,Loan_Status
0,41.451282,87559.0,677.0,67443.0,26,1,not graduate,no,Approved
1,44.000000,25955.0,661.0,11896.0,16,1,graduate,no,Approved
2,52.000000,18000.0,784.0,19197.0,27,4,graduate,no,Approved
3,21.000000,28647.0,652.0,58469.0,0,3,graduate,no,Approved
4,21.000000,78620.0,772.0,46738.0,0,4,graduate,no,Approved
...,...,...,...,...,...,...,...,...,...
595,38.000000,66089.0,700.0,125456.0,13,1,graduate,no,Approved
596,47.000000,92117.0,661.0,112690.0,22,3,graduate,yes,Approved
597,37.000000,49084.0,530.0,56922.0,17,0,graduate,yes,Approved
598,53.000000,74572.0,700.0,138755.0,29,3,graduate,no,Approved
599,57.000000,38360.0,709.0,62037.0,31,3,graduate,no,Approved

In [101]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               600 non-null    float64
 1   Annual_Income     600 non-null    float64
 2   Credit_Score      600 non-null    float64
 3   Loan_Amount       600 non-null    float64
 4   Employment_Years  600 non-null    int64
 5   Dependents        600 non-null    int64
 6   Education         600 non-null    str
 7   Self_Employed     600 non-null    str
 8   Loan_Status       600 non-null    str
dtypes: float64(4), int64(2), str(3)
memory usage: 53.7 KB